---
title: "tidy data"
output: html_document
date: "2022-09-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)

options(tibble.print_min = 5)
```

```{r}
pulse_df = haven::read_sas('./data_import_examples/public_pulse_data.sas7bdat') %>%
  janitor::clean_names() %>% 
pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = 'visit',
    values_to = 'bdi',
    names_prefix = 'bdi_score_'
  ) %>% 
  mutate(
    visit = replace(visit, visit == 'bl','00m'),
    visit = factor(visit)
 ) %>% 
  arrange(id,visit)
  
```

```{r}
litters = read_csv('./data_import_examples/FAS_litters.csv') %>% 
  janitor::clean_names() %>% 
  select(litter_number, ends_with('weight')) %>% 
pivot_longer(
  gd0_weight:gd18_weight,
  names_to = "gd",
  values_to = "weight"
) %>% 
  mutate(gd = recode(gd, 'gd0_weight' = 0, 'gd18_weight' =18))

```

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
analysis_result_wide = pivot_wider(
  analysis_result,
  names_from = 'time',
  values_from = 'mean'
)
```

```{r}
fellowship_ring = readxl::read_excel('./data_import_examples/LotR_words.xlsx', range = "B3:D6") %>% 
mutate(movie = "fellowship_ring")


two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = 'gender',
    values_to = 'words'
  ) %>% 
  mutate(race = str_to_lower(race))
```

```{r}
pup_data = 
  read_csv("./data_import_examples/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
mutate(
    sex = recode(sex, `1` = "male", `2` = "female"),
    sex = factor(sex))

litter_data = 
  read_csv("./data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

fas_data =left_join(pup_data,litter_data, by ="litter_number")
```


