---
title: "Data Import"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```


## Data Import: CSVs

Let's import data using the "reader" template
```{r}
litters_df = read.csv("data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

Look at the data

```{r}
View(litters_df)
```


```{r}
skimr::skim(litters_df)
```

# Arguments to read

"read_csv" options...
```{r}
read_csv("data_import_examples/FAS_litters.csv", na= c("", "NA", 999, 88), skip = 2)
head(litters_df)
litters_df = read.csv("data_import_examples/FAS_litters.csv", col_types = "ccdddddd")
```
## Other file formats

```{r}

mlbll_data= read_excel("data_import_examples/mlb11.xlsx", n_max
= 20)
head(mlbll_data, 5)

Lotr_words_df = 
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "B3:D6"
  )
``` 
## STill more file formats
Let's read into a sas dataset

```{r}
pulse_df = read_sas("data_import_examples/public_pulse_data.sas7bdat")
pulse_df
```


##Data export
```{r}
write_csv(Lotr_words_df, file = "Results/LotR_Words.csv")
```


## Why not base r??

```{r}
dont_do_this_df = read.csv("data_import_examples/FAS_litters.csv")
```

